const GET_NEWS_REQUEST = 'GET_NEWS_REQUEST'
const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS'
const GET_NEWS_ERROR = 'GET_NEWS_ERROR'

const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR'

const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST'
const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS'
const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR'
const UNLOGIN = 'UNLOGIN'

export {
	GET_NEWS_ERROR,
	GET_NEWS_REQUEST,
	GET_NEWS_SUCCESS,
	GET_PROFILE_REQUEST,
	GET_PROFILE_SUCCESS,
	GET_PROFILE_ERROR,
	POST_LOGIN_REQUEST,
	POST_LOGIN_SUCCESS,
	POST_LOGIN_ERROR,
	UNLOGIN,
}
